establish vpn connection before starting qbit

diff --git a/applications/kubernetes/media/qbittorrent/deployment.yml b/applications/kubernetes/media/qbittorrent/deployment.yml
--- a/applications/kubernetes/media/qbittorrent/deployment.yml
+++ b/applications/kubernetes/media/qbittorrent/deployment.yml
@@ -12,6 +12,41 @@ spec:
       labels:
         app: qbittorrent
     spec:
+      initContainers:
+      - image: qmcgaw/gluetun:latest
+        name: gluetun
+        env:
+          - name: VPN_SERVICE_PROVIDER
+            value: protonvpn
+          - name: VPN_TYPE
+            value: wireguard
+          - name: VPN_PORT_FORWARDING
+            value: "on"
+          - name: WIREGUARD_MTU
+            value: "1410"
+          - name: WIREGUARD_PRIVATE_KEY
+            valueFrom:
+              secretKeyRef:
+                key: WIREGUARD_PRIVATE_KEY
+                name: proton-secrets
+        securityContext:
+          capabilities:
+            add:
+              - NET_ADMIN
+      
+      - name: ping
+        image: busybox
+        command:
+        - sh
+        - -c
+        - |
+          sleep 30
+          while ! ping -c 1 8.8.8.8; do
+            echo "Ping failed, retrying in 5"
+            sleep 5
+          done
+          echo "ping succesfull, exiting"
+          
       containers:
       - image: lscr.io/linuxserver/qbittorrent:latest
         name: qbittorrent
@@ -34,30 +69,6 @@ spec:
           - mountPath: /media
             name: smb
         
-      - image: qmcgaw/gluetun:latest
-        name: gluetun
-        env:
-          - name: VPN_SERVICE_PROVIDER
-            value: protonvpn
-          - name: VPN_TYPE
-            value: wireguard
-          - name: VPN_PORT_FORWARDING
-            value: "on"
-          - name: WIREGUARD_MTU
-            value: "1410"
-          - name: WIREGUARD_PRIVATE_KEY
-            valueFrom:
-              secretKeyRef:
-                key: WIREGUARD_PRIVATE_KEY
-                name: proton-secrets
-        volumeMounts:
-          - name: tun
-            mountPath: /dev/net/tun
-        securityContext:
-          capabilities:
-            add:
-              - NET_ADMIN
-
       volumes:
         - name: smb
           persistentVolumeClaim:
@@ -65,8 +76,4 @@ spec:
         - name: arrstack
           persistentVolumeClaim:
             claimName: qbittorrent-pvc
-        - name: tun
-          hostPath:
-            path: /dev/net/tun
-            type: CharDevice
       restartPolicy: Always
